import { storage } from '@/db/storage';
export const dynamic='force-dynamic';
const json=(v:unknown,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(req:Request){return handle(req);}
export async function POST(req:Request){return handle(req);}
async function handle(req:Request){
 const owner=req.headers.get('oai-authenticated-user-id');if(!owner)return json({error:'Entre com sua conta para acessar o caderno.'},401);
 if(req.method==='POST' && req.headers.get('origin')!==new URL(req.url).origin)return json({error:'Origem inválida.'},403);
 try{const {db,bucket}=storage();const url=new URL(req.url);const fileId=url.searchParams.get('file');
 if(req.method==='GET' && fileId){const f=await db.prepare('SELECT * FROM files WHERE id=? AND owner=?').bind(fileId,owner).first<any>();if(!f)return json({error:'Arquivo não encontrado.'},404);const obj=await bucket.get(f.key);if(!obj)return json({error:'Arquivo indisponível.'},404);return new Response(obj.body,{headers:{'Content-Type':'application/octet-stream','Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(f.name)}`,'X-Content-Type-Options':'nosniff','Cache-Control':'private, no-store'}});}
 if(req.method==='GET'){const [s,n,f,e]=await Promise.all([db.prepare('SELECT * FROM subjects WHERE owner=? ORDER BY created').bind(owner).all(),db.prepare('SELECT * FROM notes WHERE owner=? ORDER BY updated DESC').bind(owner).all(),db.prepare('SELECT id,note,name,size FROM files WHERE owner=?').bind(owner).all(),db.prepare('SELECT * FROM exams WHERE owner=? ORDER BY date, time').bind(owner).all()]);return json({subjects:s.results,notes:n.results,files:f.results,exams:e.results});}
 if(req.headers.get('content-type')?.includes('multipart/form-data')){if(Number(req.headers.get('content-length'))>22*1024*1024)return json({error:'Limite de 20 MB por arquivo.'},413);const data=await req.formData();const file=data.get('file');const note=data.get('note');if(!(file instanceof File)||typeof note!=='string'||file.size>20*1024*1024||!file.size)return json({error:'Envie um arquivo de até 20 MB.'},400);if(!await db.prepare('SELECT id FROM notes WHERE id=? AND owner=?').bind(note,owner).first())return json({error:'Página não encontrada.'},404);const id=crypto.randomUUID(),key=owner+'/'+id;await bucket.put(key,file.stream());try{await db.prepare('INSERT INTO files (id,owner,note,name,size,key) VALUES (?,?,?,?,?,?)').bind(id,owner,note,file.name.slice(0,255),file.size,key).run();}catch(e){await bucket.delete(key);throw e;}return json({id,note,name:file.name.slice(0,255),size:file.size});}
 const b=await req.json() as any;const id=typeof b.id==='string'?b.id:'';const now=new Date().toISOString();
 if(b.action==='exam'){if(typeof b.title!=='string'||!b.title.trim()||b.title.length>200||typeof b.subject!=='string'||!b.subject||typeof b.date!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(b.date)||typeof b.time!=='string'||!/^([01]\d|2[0-3]):[0-5]\d$/.test(b.time)||typeof b.content!=='string'||b.content.length>500000)return json({error:'Preencha nome, matéria, data e horário da prova.'},400);if(!await db.prepare('SELECT id FROM subjects WHERE id=? AND owner=?').bind(b.subject,owner).first())return json({error:'Matéria não encontrada.'},404);if(id){await db.prepare('UPDATE exams SET subject=?,title=?,date=?,time=?,content=? WHERE id=? AND owner=?').bind(b.subject,b.title.trim(),b.date,b.time,b.content,id,owner).run();return json({id});}const eid=crypto.randomUUID();await db.prepare('INSERT INTO exams VALUES (?,?,?,?,?,?,?,?)').bind(eid,owner,b.subject,b.title.trim(),b.date,b.time,b.content,now).run();return json({id:eid});}
 if(b.action==='delete-exam'){await db.prepare('DELETE FROM exams WHERE id=? AND owner=?').bind(id,owner).run();return json({ok:true});}
 if(b.action==='subject'){if(typeof b.name!=='string'||!b.name.trim()||b.name.length>100||!/^#[0-9a-f]{6}$/i.test(b.color))return json({error:'Confira o nome e a cor da matéria.'},400);if(id){await db.prepare('UPDATE subjects SET name=?,color=? WHERE id=? AND owner=?').bind(b.name.trim(),b.color,id,owner).run();return json({id});}const sid=crypto.randomUUID();await db.prepare('INSERT INTO subjects VALUES (?,?,?,?,?)').bind(sid,owner,b.name.trim(),b.color,now).run();return json({id:sid});}
 if(b.action==='note'){if(typeof b.summary!=='string'||b.summary.length>12000)return json({error:'O resumo deve ter até 12 mil caracteres.'},400);if(typeof b.blocks!=='string'||b.blocks.length>500000)return json({error:'Os blocos da página são muito grandes.'},400);if(typeof b.title!=='string'||!b.title.trim()||b.title.length>200||typeof b.body!=='string'||b.body.length>500000)return json({error:'Adicione um título (até 200 caracteres). O texto pode ter até 500 mil caracteres.'},400);if(!await db.prepare('SELECT id FROM subjects WHERE id=? AND owner=?').bind(b.subject,owner).first())return json({error:'Matéria não encontrada.'},404);if(id){await db.prepare('UPDATE notes SET title=?,body=?,updated=?,summary=?,blocks=? WHERE id=? AND owner=? AND subject=?').bind(b.title.trim(),b.body,now,b.summary,b.blocks,id,owner,b.subject).run();return json({id});}const nid=crypto.randomUUID();await db.prepare('INSERT INTO notes (id,owner,subject,title,body,updated,summary,blocks) VALUES (?,?,?,?,?,?,?,?)').bind(nid,owner,b.subject,b.title.trim(),b.body,now,b.summary,b.blocks).run();return json({id:nid});}
 if(b.action==='delete-file'){const f=await db.prepare('SELECT key FROM files WHERE id=? AND owner=?').bind(id,owner).first<any>();if(f){await bucket.delete(f.key);await db.prepare('DELETE FROM files WHERE id=? AND owner=?').bind(id,owner).run();}return json({ok:true});}
 if(b.action==='delete-note'||b.action==='delete-subject'){const subject=b.action==='delete-subject';const rows=await db.prepare(subject?'SELECT key FROM files WHERE owner=? AND note IN (SELECT id FROM notes WHERE subject=? AND owner=?)':'SELECT key FROM files WHERE owner=? AND note=?').bind(...(subject?[owner,id,owner]:[owner,id])).all<any>();for(const f of rows.results)await bucket.delete(f.key);if(subject)await db.prepare('DELETE FROM exams WHERE subject=? AND owner=?').bind(id,owner).run();await db.prepare(subject?'DELETE FROM subjects WHERE id=? AND owner=?':'DELETE FROM notes WHERE id=? AND owner=?').bind(id,owner).run();return json({ok:true});}
 return json({error:'Ação inválida.'},400);
 }catch(e){console.error('Notebook storage error',e);return json({error:'Não foi possível concluir. Seu texto continua na tela; tente novamente.'},503);}
}
